# Generated by Django 4.1.7 on 2023-06-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Имя пользователя"),
                ),
                ("age", models.IntegerField(verbose_name="Возраст пользователя")),
                ("height", models.IntegerField(verbose_name="Рост пользователя")),
            ],
        ),
    ]
